const resultadoDaDivis達o = (valor1, valor2) => {
        if (valor2 === 0) {
        throw new Error (`Divisor n達o pode ser igual a zero`);
    }   
        return valor1 / valor2
}; 

try {
    console.log(resultadoDaDivis達o(10, 0));
} catch(error) {
    console.log(`Houve um erro em sua divis達o: ${error.message}`)
};
